---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-2
  labels:
    role: pod-2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      role: pod-2
  template:
    metadata:
      labels:
        role: pod-2
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: pod-2-app
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 30
